# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: async_messaging/consumer_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'async_messaging/consumer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&async_messaging/consumer_service.proto\x12 accelbyte.extend.async_messaging\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/descriptor.proto\"\xb2\x01\n\x0fReceivedMessage\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12Q\n\x08metadata\x18\x03 \x03(\x0b\x32?.accelbyte.extend.async_messaging.ReceivedMessage.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xa5\x01\n\x1d\x41syncMessagingConsumerService\x12\x83\x01\n\tonMessage\x12\x31.accelbyte.extend.async_messaging.ReceivedMessage\x1a\x16.google.protobuf.Empty\"+\x8a\xb5\x18\'PlayerKilled, PlayerSaved, PlayerJoined:=\n\x13topics_subscription\x12\x1e.google.protobuf.MethodOptions\x18\xd1\x86\x03 \x01(\tBEZCgithub.com/AccelByte/extend-event-handler-go/pkg/pb/async_messagingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'async_messaging.consumer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/AccelByte/extend-event-handler-go/pkg/pb/async_messaging'
  _globals['_RECEIVEDMESSAGE_METADATAENTRY']._loaded_options = None
  _globals['_RECEIVEDMESSAGE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ASYNCMESSAGINGCONSUMERSERVICE'].methods_by_name['onMessage']._loaded_options = None
  _globals['_ASYNCMESSAGINGCONSUMERSERVICE'].methods_by_name['onMessage']._serialized_options = b'\212\265\030\'PlayerKilled, PlayerSaved, PlayerJoined'
  _globals['_RECEIVEDMESSAGE']._serialized_start=140
  _globals['_RECEIVEDMESSAGE']._serialized_end=318
  _globals['_RECEIVEDMESSAGE_METADATAENTRY']._serialized_start=271
  _globals['_RECEIVEDMESSAGE_METADATAENTRY']._serialized_end=318
  _globals['_ASYNCMESSAGINGCONSUMERSERVICE']._serialized_start=321
  _globals['_ASYNCMESSAGINGCONSUMERSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
